### PR TITLE
feat: removed useNewUrlParser and useUnifiedTopology

### PR DESCRIPTION
**Pull request by abdinasir-Tman**

### CODE REVIEW

**Review by isasharafdin — COMMENTED** [review]
cool, thanks before i approve make last touch i mean check that template Insha'Allah!

**Comment by abdinasir-Tman** [comment]
> cool, thanks before i approve make last touch i mean check that template Insha'Allah!

I Completed bro and Checked !

**Review by isasharafdin — COMMENTED** [review]
yeh. but i see package-lock.json and .env have your private url so remove them bro

**Comment by abdinasir-Tman** [comment]
> yeh. but i see package-lock.json and .env have your private url so remove them bro

yeah. i'll remove it but it is not very important

**Comment by abdinasir-Tman** [comment]
check it now bro

**Review by isasharafdin — APPROVED** [review]
approved! thanks bro

**Pull request merged**
