### PR TITLE
Tood

### PR DESCRIPTION
**Pull request by Omar-Tood**

### CODE REVIEW

**Review by isasharafdin — COMMENTED** [review]
eng change the ts config.

**Review by isasharafdin — COMMENTED** [review]
eng where is initialconfig.ts?

**Comment by Omar-Tood** [comment]
> eng where is initialconfig.ts?

We don't need engr because we are using typescript and prisma you got it.

**Review by isasharafdin — COMMENTED** [review]
please correct the app and add config folder

**Review by isasharafdin — COMMENTED** [review]
please fix the initial.config.ts

**Comment by Omar-Tood** [comment]
> please fix the initial.config.ts

Alright Thanks pro.

**Review by isasharafdin — COMMENTED** [review]
cool, thanks

**Pull request merged**
